### ISSUE TITLE
Allow to change label of "Complete" button

### ISSUE THREAD

**Issue by DarthJapan** [stepstone-tech/android-material-stepper#107]
It would be nice if there were method setCompleteButtonLabel or setNextButtonLabel was working on this button

**Comment by zawadz88** [comment]
Hi @DarthJapan,
You should be able to change the button labels programmatically by following the steps described here: https://github.com/stepstone-tech/android-material-stepper#changing-button-labels--compound-drawables-per-step

Please let me know if this helps.

**Comment by Yasir-Ghunaim** [comment]
Hi @zawadz88,
`StepViewModel.setNextButtonLabel()` method doesn't seem to be changing **Complete** button label. 

In `StepperLayout.java`, mCompleteNavigationButton text can only be changed through this attribute: 
`StepperLayout_ms_completeButtonText` which I had to eventually use after realizing that there was no method to access mCompleteNavigationButton text programmatically.

**Comment by zawadz88** [comment]
Hi @Yasir-Ghunaim,
Thanks for clarification - it wasn't quite clear to me which API @DarthJapan was referring to.
It is exactly as you said - `StepViewModel.setNextButtonLabel()` is not meant to change the Complete button label as the Next button and Complete button are two different buttons with different styles. To change the Complete button label you need use `ms_completeButtonText` attribute on StepperLayout.

I'll add this in **README** so that it is clear.

Regarding the proposed changes - `setCompleteButtonLabel(...)` seems like a good candidate to me and I'll gladly accept any PRs regarding this!

**Comment by tobiasschuerg** [comment]
Would like to see this too. Setting properties in xml only is fine for *static* content but once anything can change dynamically there should be *programmatic* accessors.

**Comment by zawadz88** [comment]
Merged to develop, this will be in the next release.
Thanks for contributing everyone!
