### ISSUE TITLE
Next and Back Button next to each other

### ISSUE THREAD

**Issue by sophiefonseca** [stepstone-tech/android-material-stepper#164]
Hello!

I was wondering how to implement a way to make the next and back button sit beside each other and not apart? Add maybe add some padding around it?

Thank you!

**Comment by zawadz88** [comment]
Hi @sophiefonseca,
You might need to add this library as a module and edit `ms_stepper_layout.xml.xml` so that these buttons are beside each other. Alternatively, I guess that just copying this file to your project and editing it there might do the trick as well, but I'm not 100% sure about that.

Please let me know if it worked!

**Comment by zawadz88** [comment]
Hi @sophiefonseca,
Any luck?
