### ISSUE TITLE
request UI challenge

### ISSUE THREAD

**Issue by jjhesk** [stepstone-tech/android-material-stepper#192]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [x] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

Would like the propose a progress bar on the top to tracking the flow to continue.

**Comment by zawadz88** [comment]
Hi,
Could you provide more details please? Where should this progress bar be? Should it replace something else? When should it show? An image would be very helpful here ;)

**Comment by jjhesk** [comment]
![screen shot 2017-09-01 at 12 42 15](https://user-images.githubusercontent.com/629338/29955561-3923ecf8-8f13-11e7-8d77-42b325a5e559.png)
yes the red boxed deign are the current design. what is the configuration to make this work?

**Comment by zawadz88** [comment]
Hi @jjhesk,
Thanks for the explanation. In short, this is not possible with the library.
I'd suggest forking the library/making a local version of the library and changing the UI so that it's aligned with the design you provided. But there's no quick way to do it I guess.

These UI changes are not really a part of Material guidelines and don't look Material to me TBH so they're not really in scope of what the library should be doing.

Sorry for the disappointing answer :/
