### ISSUE TITLE
Add error state on step

### ISSUE THREAD

**Issue by arslancharyev31** [stepstone-tech/android-material-stepper#32]
It would be nice to add support for enabling error state as shown in the picture below. 
![components_acux_stepper_altlblplerr_rl](https://cloud.githubusercontent.com/assets/20893266/20764243/64a38bac-b73e-11e6-8644-92a93cd62df3.png)

**Comment by zawadz88** [comment]
Hi, this looks like a cool enhancement :) I'm not sure about the actual implementation though as the official documentation does not really specify when to show and hide the error state. I would assume the following:
1. When we enter a step which requires some action to go to the next step -> show regular state
2. When we press NEXT and the verification fails -> show error state

However I am not sure when to change from the error state to regular state... Should we change it in the following scenarios?
1. When we click the NEXT button and rerun the verification and it passes? 
2. When we go to the previous step? If so, when we then go back to the failed step the regular state should be shown instead of the error state?

Should there be a method for clearing the error state directly from the fragment (might be useful with input fields)?

What do you think?

**Comment by leonardo2204** [comment]
I really think as a cool enhancement also !
Giving my 2 cents:
The "show error" flow looks nice to me, as soon as the user tries to continue, validate.
As of the second part, I think that there should be something like `boolean shouldContinueOnError()`. So the continue and go back or don't continue flow should be up to the user.
IMHO I'd go with the second option, never allowing the user to continue unless all stuff is correct.

Thanks :)

**Comment by arslancharyev31** [comment]
I agree with all options listed by @zawadz88, especially with method for setting error and regular state manually.

**Comment by leonardo2204** [comment]
@arslancharyev31, take a look at #43, see if it fits your needs !

**Comment by zawadz88** [comment]
This is now released in 2.1.0.
Thanks @arslancharyev31 and @leonardo2204!
