### ISSUE TITLE
Strange issue in createStep

### ISSUE THREAD

**Issue by jagan999** [stepstone-tech/android-material-stepper#35]
I love your stepper but am now stumped with an issue. Here's how I am using your library and where I am getting stumped. 

I have 7 steps in my wizard, each implemented by a Fragment that extends Step. In the overridden createStep method, I have this code.

        @Override
        public Fragment createStep(int position) {
            Logger.writeToLog("position=" + position);
            switch (position) {
                case 0:
                    return new StepWelcome();
                case 1:
                    return new StepSelectAccounts();
                case 2:
                    return new StepPreTaxEarnings();
                case 3:
                    return new StepTaxes();
                case 4:
                    return new StepRetirals();
                case 5:
                    return new StepStockPurchase();
                case 6:
                    return new StepSummary();
                default:
                    throw new IllegalArgumentException("Unsupported position: " + position);
            }
        }

I am returning 7 in getCount() in my AbstractStepAdapter extension

What I find funny is that the initial log print shows the following when the wizard is invoked. It should have ideally only printed upto position=6 and should have printed position=0 since we're now on the first step of the wizard when it is started. However, it prints position=1 as well when the stepper is now on the first step.

2016-12-14 19:29:48:position=0
2016-12-14 19:29:48:position=1
2016-12-14 19:29:48:position=2
2016-12-14 19:29:48:position=3
2016-12-14 19:29:48:position=4
2016-12-14 19:29:48:position=5
2016-12-14 19:29:48:position=6
2016-12-14 19:29:48:position=0
2016-12-14 19:29:48:position=1

Because of this issue, when I move through the steps, I am getting wrong behavior since the step positions are now already incremented by 1 because of the behavior above. I am happy to paste the entire code if needed. This is frustrating and I don't know what I did wrong

**Comment by zawadz88** [comment]
Hi @jagan999 , I cannot reproduce this. What I'm getting in the sample app is:

> 12-15 16:34:12.783 20403-20403/com.stepstone.stepper.sample I/System.out: position: 0
12-15 16:34:12.783 20403-20403/com.stepstone.stepper.sample I/System.out: position: 1
12-15 16:34:15.055 20403-20403/com.stepstone.stepper.sample I/System.out: position: 2
12-15 16:34:15.709 20403-20403/com.stepstone.stepper.sample I/System.out: position: 3
12-15 16:34:16.258 20403-20403/com.stepstone.stepper.sample I/System.out: position: 4
12-15 16:34:16.825 20403-20403/com.stepstone.stepper.sample I/System.out: position: 5
12-15 16:34:17.401 20403-20403/com.stepstone.stepper.sample I/System.out: position: 6

Could you provide more details?

**Comment by jagan999** [comment]
Thanks for the reply. Here's my wizard activity complete with all steps. It may not work just like that since it has lot of links to my app code/logic. Can you tell me if there's an issue if the steps are static inner classes rather than separate fragment classes outside the wizard activity. I'm stuck on this, so any help will be great.


[Salary.zip](https://github.com/stepstone-tech/android-material-stepper/files/655423/Salary.zip)

**Comment by zawadz88** [comment]
Hi, I cannot think why it would be an issue however I would strongly recommend extracting them to outer classes to improve readability. I cannot really tell much from this partial code, however the expected output in the console logs should be actually:

2016-12-14 19:29:48:position=0
2016-12-14 19:29:48:position=1

Since the next steps should be only created when they user actually reaches them. Are you sure you aren't using the adapter in any other ways?

**Comment by jagan999** [comment]
Well, I'm truly stuck now. I copied your sample classes as attached, then invoked StyledTabsActivity from the same code that invoked my original wizard activity. It still prints out as follows when I expected it to only print position = 0, position = 1, position = 2 and then position = 0 since it goes to the first step in the StyledTabsActivity when launched. I'm really clueless as to why it behaves differently. Any hints? Here's what the AbstractStepperActivity printed out. I took your sample and added logging of position in createStep.

2016-12-18 12:14:34:position=0
2016-12-18 12:14:34:position=1
2016-12-18 12:14:34:position=2
2016-12-18 12:14:34:position=0
2016-12-18 12:14:34:position=1

[StepperSample.zip](https://github.com/stepstone-tech/android-material-stepper/files/659289/StepperSample.zip)

**Comment by zawadz88** [comment]
Hi @jagan999,
I've discovered why we had a discrepancy. The behaviour you're describing is happening for the Material Stepper with tabs and I checked this this for the version with dots previously...
Anyway, the _createStep_ method is used in _TabsStepperType_ in _onNewAdapter_ so that we can get the title of a tab.
When I think about it now this is something that might get actually moved to the adapter itself.

I am not sure though why this causing issues in your app. What exactly are you doing in _createStep_?

**Comment by jagan999** [comment]
Yes, I observed this too when I tried playing with different stepper types. As indicated in the code I had attached previously, I'm only returning an instance of specific Step fragments in createStep. Nothing more than that.

**Comment by zawadz88** [comment]
Could you elaborate a bit more about:
"I am getting wrong behavior since the step positions are now already incremented by 1 because of the behavior above."
What do you mean by incrementing step positions? Where are you doing this?

**Comment by jagan999** [comment]
I'm not incrementing anything myself. What I meant was that the position printed out has already moved to 1 when it should have been at 0 as previously indicated. So, when I now go to step 1, it gives position value as 2, when I go to step 6, it gives position value as 7 and so on and so forth...

**Comment by zawadz88** [comment]
OK, I think I get it now. The reason you're getting these logs in the console is because StepperLayout uses ViewPager internally. By default, ViewPager if you're on page N will create page N - 1 and N + 1. So if you're starting with the first page it will create the first and the second Fragment. If you go the second page it will also create the third Fragment and so on. The position you're getting in _createStep_ is not the current step position.

**Comment by zawadz88** [comment]
Hi @jagan999, did that help solve your case?

**Comment by jagan999** [comment]
I was on vacation and did not see your comment about ViewPager. While I understand the logic behind step position returned from ViewPager, can you pl suggest how I can correctly implement my logic when the stepper passes through the steps as shown in my sample code attached previously? I've for now worked around the issue by hardcoding the logic in onStepSelected for newStepPosition=6 but am not happy with this solution, even though it works.

**Comment by zawadz88** [comment]
Hi,
I'm not really sure what's the issue still... What are you trying to achieve? Would you like to show a message when the last step is shown?

**Comment by jagan999** [comment]
Let me capture what I'm trying to do in my implementation of AbstractStepAdapter. Based on step position, sent by createStep(), I create instances of different StepperWizardStep fragments. In some of the fragments, I need to recalculate data if any of the other steps changed data. When the wizard is completed, I assemble all individual data elements from each step into a class and then create a JSON to store into the database. The issue here is that because of wrong step positions being returned by createStep() [as evidenced by the log statements in this issue thread], some of my step fragments don't get called and as a result, my recalculation fails. Hope this clarifies.

**Comment by zawadz88** [comment]
Ok, I get it now. In this case you might consider keeping that data in a common place to be used by all the fragments, e.g. in the parent Activity or a shared component (one you could e.g. inject with Toothpick). You could use Step#onSelected() to update the fragment then. As mentioned earlier, createStep() is not said to be triggered once you actually see the fragment.
Having said that, I plan to change the logic so that createStep() would not need to get called just to get the title for the tab in the future release. However, even with that done createStep() would get called for the first two fragments.

**Comment by jagan999** [comment]
I do actually have my class shared at the activity level and incrementally populate it in every step of the wizard. As stated, I'm already implementing my logic in onStepSelected but perhaps I'll move that logic to Step#onSelected like you suggest. So, you can close this issue for now since my workaround works.
