### ISSUE TITLE
Next button skip blockingstep

### ISSUE THREAD

**Issue by sam4444** [stepstone-tech/android-material-stepper#48]
Here i have used 3 fragments. When i am on first fragment and i click twice on NEXT button it's go to 2nd then 3rd step even i not called callback.gotoNextStep in second fragment.

**Comment by zawadz88** [comment]
Hi @sam4444,
Thanks for the report!
I don't quite understand the issue though. Could you provide more details about your setup?

1. Which version of the library are you using?
2. Are all your steps instances of BlockingStep? If so what are you doing once the next button is clicked?
3. Could you provide a sample/more detailed steps to reproduce since I cannot reproduce this in the sample app?

**Comment by zawadz88** [comment]
Hi @sam4444,
Could you please see the comments above? ;)

**Comment by sam4444** [comment]
HI @zawadz88 
1. Yes i use BlockingStep in all 3 Fragments
2. I am using library version material-stepper:2.1.0
3. In First fragment through me by mistake 2 times next button clicked.
4. So it's first go to second fragment then without click next button on 2nd Framgent with in a second it's go to 3rd fragment

**Comment by zawadz88** [comment]
Hi @sam4444,
The idea of a BlockingStep is to block the user from going to the next step until some  pending operation finishes. The library itself does not block the UI or show the progress - this is something that's up to the developer since there are many ways to do that e.g. show a dialog, disable the navigation buttons and show a progress bar in the current fragment, etc.

So in your case, when the user clicks the next button the first time you should probably inform him that some operation is in progress and disable going to the next step until that operation finishes.

**Comment by sam4444** [comment]
@zawadz88  you right and also this is not any big issue or serious problem. well thanks for fast replying.
