### ISSUE TITLE
How programmatically onCompleted call 

### ISSUE THREAD

**Issue by sam4444** [stepstone-tech/android-material-stepper#52]
In last Step i want to done payment procedure on click on Complete button if payment done succesfully then it's call onComplete method code how can i do this can you please guide me with this ? Through any custom method

**Comment by zawadz88** [comment]
Hi,
You can implement StepperListener to be notified when the Complete button gets clicked, e.g.

        public void onCompleted(View completeButton) {
            // call the payment API, show some progress indicator to the user, etc.
        }

Please see https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/AbstractStepperActivity.java for an example. I'm not sure if this answers your question though?

**Comment by qymspace** [comment]
I had a similar situation because the last step doesnt have its blocking step working. The nextButtonClicked isnt even called. I worked around this by adding an extra step for "Done"

**Comment by zawadz88** [comment]
Hi @sam4444 @qymspace,
The nextButtonClicked isn't called when clicking the Complete button since it's a complete button and not a next button technically speaking ;)
The reason for this is that there is no next step to go to once on the last step. Therefore, the blocking method used for previous steps is not actually required and the same could be accomplished by using _onCompleted(..)_ from the _ StepperListener_. So e.g. if you have an API call to make once you click Complete, then do that in _onCompleted(View completeButton)_.

@sam4444 Does that answer your question?

**Comment by qymspace** [comment]
Makes sense. Thanks for your kindness and awesome lib @zawadz88
