### ISSUE TITLE
Implement with viewpager

### ISSUE THREAD

**Issue by jenzoned** [stepstone-tech/android-material-stepper#57]
How to implement this with view pager?

**Comment by zawadz88** [comment]
Hi,
What do you mean exactly? StepperLayout uses a ViewPager internally

**Comment by jenzoned** [comment]
Hello,
I mean how to enable the swipe functionality? Because in the example app, swipe is disabled. Thanks!

**Comment by zawadz88** [comment]
OK, I get it now.
Short answer: swipe should not happen in this component.
Long answer:
Swiping is disabled in the library on purpose (https://github.com/stepstone-tech/android-material-stepper/blob/master/material-stepper/src/main/java/com/stepstone/stepper/internal/NonSwipeableViewPager.java).
The reason for this is because we want to do some verification before going to the next step. This is not explained explicitly in the documentation for this component (https://material.io/guidelines/components/steppers.html) however I have never seen such a behavior in this type of component.

Could you explain why would you like to be able to swipe across the steps?

**Comment by jenzoned** [comment]
I get it now why the library don't have a swipe functionality! thanks! great library also! 👍
