### ISSUE TITLE
Feature request: Stepper feedback.

### ISSUE THREAD

**Issue by arslancharyev31** [stepstone-tech/android-material-stepper#70]
Good day. Is it possible to implement a stepper feedback like the one provided in [material guidelines](https://material.io/guidelines/components/steppers.html#steppers-types-of-steppers)?

**Comment by zawadz88** [comment]
Hi,
With the current version of the library it cannot be exactly as on Google's guidelines. By using BlockingStep you should be able to change the state of the current step to show a progress bar for the duration of an operation, but showing the message instead of the tabs is not currently supported.
This looks like a nice enhancement though!

**Comment by arslancharyev31** [comment]
Looking forward to see this feature in future releases! It would look very impressive for indeterminate continious operations.

**Comment by zawadz88** [comment]
Released in 3.2.0
